### ISSUE TITLE
getBilibiliComm Fun返回的网址访问提示{}需要参数

### ISSUE THREAD

**Issue by HahhCH** [DrRyanHuang/bilibiliTool#1]
{}改为页面序号才有评论诶
是不是之前直接能出xml哦

**Comment by DrRyanHuang** [comment]
@HahhCH 
您好，代码之前写了，忘记push了，预计今天网上8点上线，现在手边没电脑，十分感谢您的issue

**Comment by DrRyanHuang** [comment]
@HahhCH 
当前的代码是不完整的

**Comment by HahhCH** [comment]
嘿嘿，我也是正好需要这个代码😆谢谢代码

Ryan_Huang <notifications@github.com>于2020年8月21日 周五下午6:04写道：

**Comment by DrRyanHuang** [comment]
@HahhCH

不好意思哈，一回家就忘了，getBilibiliComm.py 已经更新
